name: tenka_runtime
description: "ðŸš Contains the runtime of Tenka."
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    crypto: ^3.0.1
    encrypt: ^5.0.0
    fubuki_vm:
        git:
            url: https://github.com/yukino-org/fubuki.git
            path: packages/fubuki_vm
    html: ^0.15.0
    http: ^0.13.3
    meta: ^1.7.0
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx

dev_dependencies:
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git
