name: utilx
description: "ðŸ”§ Contains utility tools used in Dart projects related to Yukino Org."
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    meta: ^1.7.0

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
