name: tenka_runtime
description: "ðŸš Contains the runtime of Tenka."
version: 0.0.0

publish_to: none

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    beize_vm:
        git:
            url: https://github.com/zyrouge/beize.git
            path: packages/beize_vm
    crypto: ^3.0.3
    encrypt: ^5.0.1
    html: ^0.15.3
    http: ^1.0.0
    meta: ^1.9.1
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx

dev_dependencies:
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git
