name: extensions_dev_tools
description: Consists of developer tools for Yukino extensions.
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    colorize: ^3.0.0
    hetu_script_dev_tools: ^0.0.8
    path: ^1.8.0
    tenka:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_tenka
    utilx:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_utilx
    utilx_desktop:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_utilx_desktop
    yaml: ^3.1.0

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
